declare const BOLD: string[];
declare const CAPITAL_BOLD: string[];
declare const ITALIC: string[];
declare const CAPITAL_ITALIC: string[];
declare const UNDERLINE: string[];
declare const CAPITAL_UNDERLINE: string[];
declare const BOLD_ITALIC: string[];
declare const CAPITAL_BOLD_ITALIC: string[];
declare const BOLD_ITALIC_UNDERLINE: string[];
declare const CAPITAL_BOLD_ITALIC_UNDERLINE: string[];
export { BOLD, CAPITAL_BOLD, ITALIC, CAPITAL_ITALIC, UNDERLINE, CAPITAL_UNDERLINE, BOLD_ITALIC, CAPITAL_BOLD_ITALIC, BOLD_ITALIC_UNDERLINE, CAPITAL_BOLD_ITALIC_UNDERLINE, };
